### INtroduction

In [9]:
import numpy as np
li_arr=[i for i in range(0,100)]
np_arr=np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [14]:
print(np_arr.itemsize)
print(np_arr.itemsize * np_arr.size)

4
400


In [22]:
import sys
a=10
print(sys.getsizeof(a))
print(sys.getsizeof(1)*len(li_arr))

28
2800


## Time Execution difference

In [2]:
import numpy as np
import time

size=100000

def addition_using_list():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i] + b[i] for i in range(size)]
    t2=time.time()
    return (t2-t1)

def addition_using_numpy():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    t2=time.time()
    return (t2-t1)
t_list=addition_using_list()
t_numpy=addition_using_numpy()
print("list=",t_list*1000)
print("numpy=",t_numpy*1000)


list= 62.82687187194824
numpy= 1.054525375366211


## creating numpy array

In [84]:
import numpy as np

a=[1,2,3,4,5]
b=np.array(a)
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [86]:
import numpy as np

a=[1,2,3,4,5,'a']
b=np.array(a)
print(b)
    

['1' '2' '3' '4' '5' 'a']


In [88]:
import numpy as np

a=[1,2,3,4,5,'a']
b=np.array(a,dtype=int)
print(b)

ValueError: invalid literal for int() with base 10: 'a'

In [89]:
import numpy as np

a=[1,2,3,4,5]
b=np.array(a,dtype=int)
print(b)

[1 2 3 4 5]


### Functions in numpy array

In [91]:
b=np.ones(3)
b

array([1., 1., 1.])

In [92]:
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [95]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [96]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [98]:
b=np.zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [101]:
b=np.full(3,5,dtype=float)
b

array([5., 5., 5.])

In [102]:
b=np.full((3,3),5,dtype=float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [104]:
b=np.empty([2, 2])
b

array([[4.00536722e-307, 1.78019082e-306],
       [4.45036841e-307, 1.44635488e-307]])

In [105]:
b=np.empty([2, 2],dtype=int)
b

array([[ -255346783, -1594464417],
       [-2071983101,   777521141]])

In [108]:
import numpy as geek 
  
b = geek.empty(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = geek.empty([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = geek.empty([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b : 
 [7667823 7209074]

Matrix a : 
 [[16843009 16843009]
 [16843009 16843009]]

Matrix c : 
 [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


## Create numpy array-2

In [111]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
b=np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

## LineSpaces

In [116]:
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [65]:
b=np.linspace(2,10,5,dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [42]:
b=np.linspace(2,10,5,dtype=int,endpoint=False)
b

array([2, 3, 5, 6, 8])

In [124]:
b=np.linspace(2,10,5,dtype=int,endpoint=False,retstep=True)
b

(array([2, 3, 5, 6, 8]), 1.6)

In [3]:
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
b=np.identity(3,4) #we can only have n* n matrix
b 

TypeError: data type not understood

In [6]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
b=np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [10]:
b=np.random.rand(3)
b

array([0.22827539, 0.54733727, 0.9561914 ])

In [12]:
b=np.random.rand(2,3)
b

array([[0.34069297, 0.73533388, 0.96732325],
       [0.34911269, 0.12113818, 0.33864001]])

In [30]:
b=np.random.rand(10)*10
b

array([3.34671226, 9.2693454 , 0.82523293, 4.61661756, 0.32037126,
       1.39901644, 0.73572613, 9.07150098, 8.2959229 , 9.36168789])

In [37]:
a = np.array([[0, 1, 2, 3],[0, 1, 2, 3]])
a.shape

(2, 4)

In [7]:
import numpy as np
np.random.rand()

0.4310031599290908

In [2]:
import numpy as np
np.random.randint(10, 4)

ValueError: low >= high

In [46]:
import numpy as np
b=np.linspace(9,49)
b=str(b)[1:-1]
print(b)

 9.          9.83673469 10.67346939 11.51020408 12.34693878 13.18367347
 14.02040816 14.85714286 15.69387755 16.53061224 17.36734694 18.20408163
 19.04081633 19.87755102 20.71428571 21.55102041 22.3877551  23.2244898
 24.06122449 24.89795918 25.73469388 26.57142857 27.40816327 28.24489796
 29.08163265 29.91836735 30.75510204 31.59183673 32.42857143 33.26530612
 34.10204082 34.93877551 35.7755102  36.6122449  37.44897959 38.28571429
 39.12244898 39.95918367 40.79591837 41.63265306 42.46938776 43.30612245
 44.14285714 44.97959184 45.81632653 46.65306122 47.48979592 48.32653061
 49.16326531 50.        


In [136]:
import numpy as np
b=np.linspace(0,5,10)[1:]
ab=np.round(b, 2)
print(ab)
print(ab[1]-ab[0])
print(ab[2]-ab[1])
print(ab[3]-ab[2])
print(ab[4]-ab[3])
print(ab[5]-ab[4])

[0.56 1.11 1.67 2.22 2.78 3.33 3.89 4.44 5.  ]
0.55
0.5599999999999998
0.5500000000000003
0.5599999999999996
0.5500000000000003


In [91]:
import numpy as np

def split_into_parts(number, n_parts):
    return np.linspace(0, number, n_parts+1)[1:]

ans=split_into_parts(5, 9)
ans=np.round(ans, 2)
for row in ans:
    print(row)



0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
5.0


In [171]:
import numpy as np

li=[1,2,3,4,5]
arr=np.array(li)
print(arr)

[1 2 3 4 5]


In [172]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [176]:
print(li[3])
print(arr[3])
# Slicing the num-array
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [179]:
import numpy as np

li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [177]:
print(arr_2d.data)
print(arr_2d.shape)

print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [182]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])

10
10
10


## 2D-SLICING

In [183]:
print(li_2d[1][:3])
print(arr_2d[1][:3])

[5, 6, 7]
[5 6 7]


In [185]:
print(li_2d[:3][3])

IndexError: list index out of range

In [187]:
print(arr_2d[0:3,2])

[ 3  7 11]


In [191]:
print(arr_2d[2:4,1:3])

[[10 11]
 [14 15]]


In [193]:
print(li_2d[2:4][1:3])

[[13, 14, 15, 16]]


In [200]:
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
input_



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [237]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
a=input_[2,0:3]
a=str(a)[1:-1]
b=input_[1:4,3]
b=str(b)[1:-1]
c=input_[2:4,0:6]
c=str(c)[1:-1]
c=c.replace('[','')
c=c.replace(']','')
d=input_[1:3,1:3]

d=str(d)[1:-1]
d=d.replace('[','')
d=d.replace(']','')
print(a)
print(b)
print(c)
print(d)

11 12 13
 9 14 19
11 12 13 14 15
 16 17 18 19 20
 7  8
 12 13


In [272]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
a=input_[2,0:3]
b=input_[1:4,3]
c=input_[2:4,0:6]

d=input_[1:3,1:3]
for row in a:
    print(row,end=' ')
print('')
for row in b:
    print(row,end=' ')
print('')
for row in c:
    row=str(row)
    row=row.replace('[','')
    row=row.replace(']',' ')
    print(row,end='')
print('')
for row in d:
    row=str(row)
    row=row.replace('[','')
    row=row.replace(']',' ')
    print(row,end='')

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

In [22]:
import numpy as np
np.random.randint(5, size=(2, 4))

array([[2, 0, 0, 2],
       [2, 2, 2, 0]])

## Mathematical opefration on numpy arrray

In [30]:
import numpy as np
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[12  4  2 14 17]
[11  4  4  6  3]


In [31]:
a=a+1
a


array([13,  5,  3, 15, 18])

In [33]:
c=a+b
c

array([24,  9,  7, 21, 21])

In [35]:
d=a*b
d

array([143,  20,  12,  90,  54])

In [36]:
f=a/b
f

array([1.18181818, 1.25      , 0.75      , 2.5       , 6.        ])

In [38]:
g=a // b
g

array([1, 1, 0, 2, 6], dtype=int32)

In [39]:
h=a**b
h

array([1159031605,        625,         81,   11390625,       5832],
      dtype=int32)

In [40]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[13  5  3 15 18]
54
10.8
3
2
18
4


In [42]:
print(a)
print(b)

[13  5  3 15 18]
[11  4  4  6  3]


In [43]:
a>b

array([ True,  True, False,  True,  True])

In [44]:
a<b

array([False, False,  True, False, False])

In [45]:
a==b

array([False, False, False, False, False])

In [47]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [48]:
print(np.logical_not(a))

[False False False False False]


## Boolean indexing

In [53]:
import numpy as np
a=np.array(['t','b','r','d','e','f','z','a'])
b=np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[14 18  9  7 19 12 18  3]


In [55]:
print(b>10)

[ True  True False False  True  True  True False]


In [57]:
bool_arr=b>10
print(bool_arr)
new_arr=b[bool_arr]
print(new_arr)

[ True  True False False  True  True  True False]
[14 18 19 12 18]


In [58]:
new_arr=b[b>10]
print(new_arr)

[14 18 19 12 18]


In [60]:
new_arr=b[(b>10) & (b<18)]
new_arr

array([14, 12])

In [68]:
print(b)
c=b
c

[10 10 10  7 10 12 10  3]


array([10, 10, 10,  7, 10, 12, 10,  3])

In [69]:
c[:3]=19

In [70]:
c

array([19, 19, 19,  7, 10, 12, 10,  3])

In [71]:
c[c>15]=100
c

array([100, 100, 100,   7,  10,  12,  10,   3])

In [72]:
ind=np.where(b==100)
ind

(array([0, 1, 2], dtype=int64),)

In [74]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   7  10  12  10   3]


In [75]:
ind=np.where(b==100)
print(ind)
print(a[ind])

(array([0, 1, 2], dtype=int64),)
['t' 'b' 'r']


In [84]:
import numpy as np
a=[1,2,0,0,4,0]
b=np.array(a)
k=np.where(b>0)
for row in k:
    row=str(row)[1:-1]
    print(row,end=' ')

0 1 4 

In [90]:
import numpy as np
l=[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]
num_arr=np.array(l)
v=np.where(num_arr%3==0)
for row in v:
    row=str(row)[1:-1]
    print(row,end=' ')
    

1 4 7 

In [103]:
import numpy as np
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
num_arr=np.array(l)
c=num_arr
c[c%2!=0]=-1
for i in c:
    print(i,end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

In [124]:
import numpy as np
l=[11, 2, 13, 4, 15, 6, 27, 8, 19]
num_arr=np.array(l)
c=num_arr

c[c.argmax()]=0
for i in c:
    print(i)

11
2
13
4
15
6
0
8
19


In [130]:
import numpy as np
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
num_arr=np.array(l)
n = (num_arr > 2) & (num_arr < 9)
num_arr[n]=num_arr[n]*-1
#print(num_arr)
for i in num_arr:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


## printing 2 numpy array side by side

In [165]:
import numpy as np
import re
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
ind=np.where(height>155)
d=(age[ind])
e=(height[ind])
print(re.sub(r' *\n *', '\n',np.array_str(np.c_[d, e]).replace('[', '').replace(']', '').strip()))

     


15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


### Indexsing in 2d array

In [4]:
import numpy as np
a=np.random.randint(1,30,(5,6))
print(a)

[[ 8  1 15 23  3 25]
 [ 3  7 16  9 29 28]
 [ 3 29 29 10 27 29]
 [24  8 27 27  7 15]
 [18  1  1 21 26 29]]


In [5]:
bool_arr=a>10
print(bool_arr)

[[False False  True  True False  True]
 [False False  True False  True  True]
 [False  True  True False  True  True]
 [ True False  True  True False  True]
 [ True False False  True  True  True]]


In [6]:
b=a
print(b)

[[ 8  1 15 23  3 25]
 [ 3  7 16  9 29 28]
 [ 3 29 29 10 27 29]
 [24  8 27 27  7 15]
 [18  1  1 21 26 29]]


In [7]:
ans=b[bool_arr]
print(ans)

[15 23 25 16 29 28 29 29 27 29 24 27 27 15 18 21 26 29]


In [8]:
b[bool_arr]=100
print(b)

[[  8   1 100 100   3 100]
 [  3   7 100   9 100 100]
 [  3 100 100  10 100 100]
 [100   8 100 100   7 100]
 [100   1   1 100 100 100]]


In [173]:
c=np.random.randint(1,10,(2,2))
print(c)

[[7 4]
 [9 6]]


In [175]:
bool_arr=np.array([[True,False],[False,True],[True,True]])
print(bool_arr)

[[ True False]
 [False  True]
 [ True  True]]


In [177]:
c=c[bool_arr]
print(c)

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [13]:
print(b)

[[  8   1 100 100   3 100]
 [  3   7 100   9 100 100]
 [  3 100 100  10 100 100]
 [100   8 100 100   7 100]
 [100   1   1 100 100 100]]


In [14]:
bool_arr=b[:,3]==100
print(bool_arr)

[ True False False  True  True]


In [20]:
b[bool_arr,3]=99
print(b)

array([ True, False, False,  True,  True])

In [230]:
import numpy as np
a=np.array( [[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[ 6,5,4,3 ,2]])
a = a[a[:,1].argsort()]
print(a)


[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


### Broadcasting

In [231]:
import numpy as np
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)

[[1 4 2]
 [7 8 3]
 [1 9 7]]
[[7 5 1]
 [7 7 7]
 [2 9 3]]


In [232]:
print(x-y)

[[-6 -1  1]
 [ 0  1 -4]
 [-1  0  4]]


In [235]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3))
print(x)
print(y)

[[6 8 7]
 [9 7 6]
 [1 6 1]]
[8 6 2]


In [236]:
print(x-y)

[[-2  2  5]
 [ 1  1  4]
 [-7  0 -1]]


In [237]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)

[[3 2]
 [7 2]
 [1 9]]
[[4 2 5]
 [2 2 8]]


In [239]:
print(x-y)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [240]:
y=np.transpose(y)
print(y)
ans=x-y
print(ans)

[[4 2]
 [2 2]
 [5 8]]
[[-1  0]
 [ 5  0]
 [-4  1]]


In [243]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [1]:
a = np.arange(6).reshape((3, 2))
a

NameError: name 'np' is not defined

## EXampmle:

In [21]:
import numpy as np
import csv
file_obj=open('Dataset/year2017_01.csv',encoding="utf8")
file_obj.close
data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
wounded=[]
country=[]
for row in data:
    killed.append(row['Killed'])
    country.append(row['Wounded'])
    wounded.append(row['Country'])
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_killed[np_killed=='']=='0.0'
np_wounded[np_wounded=='']=='0.0'

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded, dtype=float)
killed_wounded=np_killed+np_wounded
np_country=np.array(country)

bool_arr=np.country=='India'
ans=killed_wounded[bool_arr]
print(ans.sum())
print(killed_wounded.sum())


ValueError: could not convert string to float: ''

In [23]:
import numpy as np
import csv
file_obj=open('Dataset/terrorismData.csv.crdownload',encoding="utf8")
data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
country=[]
for row in data:
    killed.append(row["Killed"])
    country.append(row['Country'])
np_killed=np.array(killed)
np_country=np.array(country)

np_killed[np_killed=='']='0.0'

killed=np.array(np_killed,dtype=float)
bool_arr=np_country=='United States'
ans=np_killed[bool_arr]
ans=np.array(ans,dtype=float)
print(int(np.sum(ans)))




AttributeError: module 'numpy' has no attribute 'ans'

In [106]:
import numpy as np
import csv
file_obj=open('Dataset/terrorismData.csv.crdownload',encoding="utf8")
data=csv.DictReader(file_obj,skipinitialspace=True)
#data_list=list(data)
Day=[]
AttackType=[]
for row in data:
    Day.append(row['Day'])
    AttackType.append(row['AttackType'])
np_day=np.array(Day)
np_attackType=np.array(AttackType)


np_day[np_day=='']='0.0'
#np_attackType[np_attackType=='']='0.0'

np_day=np.array(np_day,dtype=float)
#np_attackType=np.array(np_attackType,dtype=float)

bool_val=np_day[(np_day>10) & (np_day<20)]
count=0
for i in bool_val:
    count=count+1
print(count)

    

26489


In [139]:
import numpy as np
import csv
file_obj=open('Dataset/terrorismData.csv.crdownload',encoding="utf8")
data=csv.DictReader(file_obj,skipinitialspace=True)
list_data=list(data)
l=[]
day={}
for row in list_data:
    l.append(row['Day'])
np_l=np.array(l,dtype=float)

np_l=

    


array([ 2.,  0.,  0., ..., 28., 28., 28.])

In [141]:
import numpy as np
import csv
file_obj=open('Dataset/terrorismData.csv.crdownload',encoding="utf8")
data=csv.DictReader(file_obj,skipinitialspace=True)
#data_list=list(data)
Day=[]
AttackType=[]
for row in data:
    Day.append(row['Day'])
    AttackType.append(row['AttackType'])
np_day=np.array(Day)
np_attackType=np.array(AttackType)


np_day[np_day=='']='0.0'
#np_attackType[np_attackType=='']='0.0'

np_day=np.array(np_day,dtype=float)
#np_attackType=np.array(np_attackType,dtype=float)

bool_val=np_day[(np_day>=10) & (np_day<21)]
count=bool_val.size
print(count)


32458


In [201]:
import numpy as np
import csv
file_obj=open('Dataset/terrorismData.csv.crdownload',encoding="utf8")
data=csv.DictReader(file_obj,skipinitialspace=True)

year=[]
month=[]
day=[]
for row in data:
    year.append(row['Year'])
    month.append(row['Month'])
    day.append(row['Day'])
np_year=np.array(year,dtype=float)
np_month=np.array(month,dtype=float)
np_day=np.array(day,dtype=float)

#ind=np.where(np_month==1)
#c=np_year[ind]







array([ 2.,  0.,  0., ..., 28., 28., 28.])

In [322]:

import numpy as np
import csv
with open('Dataset/terrorismData.csv.crdownload') as file :
    data = csv.DictReader(file)
    day = []
    month = []
  
    killed = []
    wounded = []
    casualty = []
    city = []
    group = []
    s = []
    
    count = 0
    for row in data :
        if "Kashmir" in row['State'] and "1999" in row['Year'] :
        
        
        
            day.append(row['Day'])
            month.append(row['Month'])
            
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
            city.append(row['City'])
            group.append(row['Group'])
        
day = np.array(day,dtype=int)
month = np.array(month,dtype=int)killed.append(row['Killed'])
            wounded.append(row['Wounded'])

killed = np.array(killed)
killed[killed == ''] = '0.0'
killed = np.array(killed , dtype = float)
killed = np.array(killed , dtype = int)

wounded = np.array(wounded)
wounded[wounded == ''] = '0.0'
wounded = np.array(wounded , dtype = float)
wounded = np.array(wounded , dtype = int)

city = np.array(city)
group = np.array(group)
# npstate = np.array(states)




#  & (state == "Jammu and Kashmir")

m = np.where((month >= 5) & (month <= 7) )
city = city[m]
group = group[m]

casualty = killed[m] + wounded[m]

index=casualty.argmax()
print(casualty.max(),city[index],group[index])














UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6235: character maps to <undefined>

In [336]:
import numpy as np
import csv
with open('Dataset/terrorismData.csv.crdownload',encoding="utf8") as file :
    data = csv.DictReader(file,skipinitialspace=True)
    state=[]
    killed=[]
    wounded=[]
    count = 0
    for row in data:
        if ('Jharkhand' in row['State']) or ('Odisha' in row['State']) or ('Andhra Pradesh' in row['State']) or ('Chhattisgarh' in row['State']):
            state.append(row['State'])
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
np_state=np.array(state)
np_killed=np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed=='']=0
np_wounded[np_wounded=='']=0

np_killed=np.array(np_killed,dtype=float)
np_killed=np.array(np_killed,dtype=int)
np_wounded=np.array(np_wounded,dtype=float)
np_wounded=np.array(np_wounded,dtype=int)

Casualty=np_killed+np_wounded
print(Casualty.sum())

2029


In [321]:
import numpy as np
import csv
file_obj=open('Dataset/terrorismData.csv.crdownload',encoding="utf8")
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
city=[]
terror_group=[]
month=[]
year=[]
state=[]
for row in data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    city.append(row['City'])
    terror_group.append(row['Group'])
    month.append(row['Month'])
    year.append(row['Year'])
    state.append(row['State'])
    
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_city=np.array(city)
np_state=np.array(state)
np_terror_group=np.array(terror_group)
np_month=np.array(month,dtype=float)
np_year=np.array(year,dtype=float)
mon=np.where((np_month>=5) & (np_month<=7) & (np_year==1999) & (np_state=='Jammu and Kashmir'))
np_year=np_year[mon]
np_city=np_city[mon]
np_terror_group=np_terror_group[mon]
np_killed=np_killed[mon]
np_wounded=np_wounded[mon]

np_killed[np_killed=='']=0
np_wounded[np_wounded=='']=0

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
#Casualty=np_killed+np_killed

Casualty=np_killed+np_wounded
ind=Casualty.argmax()

print(int(Casualty[ind]),np_city[ind],np_terror_group[ind])

22 Kargil District Separatists


In [3]:
import numpy as np
import csv
file_obj=open('Dataset/terrorismData.csv.crdownload',encoding="utf8")
data=csv.DictReader(file_obj,skipinitialspace=True)

state=[]
killed=[]
wounded=[]
for row in data:
    state.append(row['State'])
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
np_state=np.array(state)
np_killed=np.array(killed)
np_wounded=np.array(wounded)
a=np.where(np_state=='Jharkhand')
b=np.where(np_state=='Odisha')
c=np.where(np_state=='Andhra Pradesh')
d=np.where(np_state=='Chhattisgarh')
print(b)
np_killed[np_killed=='']=0
np_wounded[np_wounded=='']=0

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)




(array([39416, 74478], dtype=int64),)


### important way of dict operation

####

In [65]:
import numpy as np
import csv
with open('Dataset/terrorismData.csv.crdownload',encoding="utf8") as file_obj :
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if 'India' in row['Country'] and 'Unknown' not in row['City']:
            city.append(row['City'])
            wounded.append(row['Wounded'])
            killed.append(row['Killed'])
    np_wounded=np.array(wounded)
    np_killed=np.array(killed)
    np_city=np.array(city)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_wounded+np_killed, dtype='int')
    
    
    citydic={}

    for i in range(len(np_city)):
        if np_city[i] in citydic:
            citydic[np_city[i]]+=np_casuality[i]
        else:
            citydic[np_city[i]]=np_casuality[i]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]

    

Srinagar 2939
New Delhi 1919
Mumbai 1424
Jammu 1115
Amritsar 766


In [88]:
import numpy as np
import csv
with open('Dataset/terrorismData.csv.crdownload',encoding="utf8") as file_obj :
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if 'India' in row['Country'] and 'Unknown' not in row['City']:
            city.append(row['City'])
            wounded.append(row['Wounded'])
            killed.append(row['Killed'])
    np_wounded=np.array(wounded)
    np_killed=np.array(killed)
    np_city=np.array(city)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_wounded+np_killed, dtype='int')
    
    citydic={}

    for i in range(len(np_city)):
        if np_city[i] in citydic:
            citydic[np_city[i]]+=np_casuality[i]
        else:
            citydic[np_city[i]]=np_casuality[i]
    
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]



Srinagar 2939


In [78]:
import numpy as np
import csv
with open('Dataset/terrorismData.csv.crdownload',encoding="utf8") as file_obj :
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])
    np_day=np.array(day, dtype='int')
    day, count=np.unique(np_day, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])

1 3352
